import OpenAI from 'openai';

/**
 * Class for handling interactions with OpenAI's GPT model for chat completion.
 */
export default class ChatGPT {
  /**
 * Constructor for the ChatGPT class.
 * @param {string} api_key - The API key for OpenAI authentication.
 */
  constructor(api_key) {
    this.openai = new OpenAI({
      apiKey: api_key,
    });
  }

  /**
   * Generates a completion based on the provided question using the OpenAI chat model.
   * @param {string} question - The user's input or question.
   * @returns {Promise<string>} - A Promise resolving to the response text generated by GPT.
   */
  async prompt(question) {
    try {
      const resp = await this.openai.chat.completions.create({
        messages: [{ role: 'user', content: question }],
        model: 'gpt-3.5-turbo',
      });
      return resp.choices[0].message.content;
    }
    catch (e) {
      console.log(e);
    }
  }
}